apiVersion: v1
kind: Service
metadata:
  name: db #must be db bec. worker app expects this 
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
    - port: 5432 #port for postgres
      targetPort: 5432
      #no need to specify nodePort
  selector: #to link the service to the pod, must specify
            #same labels configured for the pod
    name: postgres-pod #label name
    app: demo-voting-app 

#this is an internal service not to be exposed out to the network