apiVersion: v1
kind: Service
metadata:
  name: result-service #name of service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80 #front end app runs on port 80
      targetPort: 80
      #no need to specify nodePort
      nodePort: 30005
  selector: #to link the service to the pod, must specify
            #same labels configured for the pod
    name: result-app-pod #label name
    app: demo-voting-app 

#this is an internal service not to be exposed out to the network