apiVersion: v1 
kind: Pod
metadata:
  name: result-app-pod #name of pod
  labels: 
    name: result-app-pod #label name
    app: demo-voting-app 
spec:
  containers:
    - name: result-app #name of the container
      image: kodekloud/examplevotingapp_result:v1 #custom image built from docker repo
      ports: 
        - containerPort: 80 #port on which the app listens for the voting app
        