apiVersion: v1
kind: Service
metadata:
  name: voting-service #name of service
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
    - port: 80 #front end app runs on port 80
      targetPort: 80
      nodePort: 30004

  selector: #to link the service to the pod, must specify
            #same labels configured for the pod
    name: voting-app-pod #label name
    app: demo-voting-app 

#supposed to be externally accessible hence nodePorr