apiVersion: v1 
kind: Pod
metadata:
  name: voting-app-pod #name of pod
  labels: 
    name: voting-app-pod #label name
    app: demo-voting-app #name of application
    #will use this name for all components part 
    #of this app stack so I can group the components 
    #of a single application by assigning 
    #the same label to all of them 
spec:
  containers:
    - name: voting-app #name of the container
      image: kodekloud/examplevotingapp_vote:v1 #custom image built from docker repo
      ports: 
        - containerPort: 80 #port on which the app listens for the voting app
        