apiVersion: v1 
kind: Pod
metadata:
  name: worker-app-pod #name of pod
  labels: 
    name: worker-app-pod #label name
    app: demo-voting-app 
spec:
  containers:
    - name: worker-app #name of the container
      image: kodekloud/examplevotingapp_worker:v1 #custom image built from docker repo
#worker app has no services listening, so no port def. required 
